### ISSUE TITLE
Link to first slides wrong

### ISSUE THREAD

**Issue by dermitdemk** [pjercic/FoundationsOfCSS2024#1]
In the README there is this link to the first week slide: "https://pjercic.github.io/FoundationsOfCSS2024/01_Introduction/week-1.pdf". This link response with a 404 File not found, the slides are actually in this path: "https://pjercic.github.io/FoundationsOfCSS2024/Lectures/week-1-2024.pdf".

**Comment by pavlesav** [comment]
Thanks for pointing that out! Fixed now.
